services:
  mongodb:
    image: mongo:7.0
    container_name: books_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: books_crawler
    volumes:
      - mongodb_data:/data/db
    networks:
      - books_network

volumes:
  mongodb_data:
    driver: local

networks:
  books_network:
    driver: bridge

